---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Install Docker daemon.json
  copy:
    content: "{{ docker_daemon_json | to_json }}"
    dest: "{{ docker_daemon_json_filename }}"
    mode: "0644"
    owner: root
    group: root
  notify: restart docker
  when:
    - "docker_daemon_json|bool"

- name: Clean out Docker daemon.json
  file:
    path: "{{ docker_daemon_json_filename }}"
    state: absent
  when:
    - "not docker_daemon_json|bool"
    - "docker_daemon_json_filename|length > 0"

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0
